-- LIVE SUPABASE ENUM DEFINITIONS

CREATE TYPE public.account_status AS ENUM ('active', 'pending', 'suspended', 'restricted', 'deleted');
CREATE TYPE public.appointment_status AS ENUM ('scheduled', 'confirmed', 'completed', 'cancelled', 'no_show');
CREATE TYPE public.beneficiary_type AS ENUM ('individual', 'business', 'mobile_money', 'bank_account');
CREATE TYPE public.business_member_role AS ENUM ('OWNER', 'ADMIN', 'MANAGER', 'ACCOUNTANT', 'SALES', 'CASHIER', 'EMPLOYEE', 'VIEWER');
CREATE TYPE public.business_status AS ENUM ('draft', 'active', 'suspended', 'archived');
CREATE TYPE public.crm_activity_type AS ENUM ('visit', 'call', 'whatsapp', 'email', 'appointment', 'follow_up', 'delivery', 'collection', 'other');
CREATE TYPE public.crm_appointment_status AS ENUM ('scheduled', 'confirmed', 'completed', 'cancelled', 'missed');
CREATE TYPE public.crm_collection_activity_type AS ENUM ('call', 'whatsapp', 'visit', 'reminder', 'payment', 'promise', 'comment');
CREATE TYPE public.crm_commission_basis AS ENUM ('sale_amount', 'collected_amount', 'fixed', 'per_unit');
CREATE TYPE public.crm_commission_status AS ENUM ('pending', 'approved', 'paid', 'cancelled');
CREATE TYPE public.crm_promise_status AS ENUM ('pending', 'kept', 'broken', 'cancelled');
CREATE TYPE public.crm_prospect_status AS ENUM ('new', 'contacted', 'qualified', 'converted', 'lost', 'archived');
CREATE TYPE public.crm_prospect_temperature AS ENUM ('hot', 'warm', 'cold');
CREATE TYPE public.crm_prospecteur_status AS ENUM ('active', 'inactive', 'suspended');
CREATE TYPE public.crm_schedule_status AS ENUM ('pending', 'partially_paid', 'paid', 'overdue', 'cancelled');
CREATE TYPE public.crm_stock_movement_type AS ENUM ('transfer', 'reception', 'sale', 'return', 'adjustment');
CREATE TYPE public.crm_target_period AS ENUM ('daily', 'weekly', 'monthly', 'yearly');
CREATE TYPE public.expense_status AS ENUM ('pending', 'approved', 'rejected', 'paid');
CREATE TYPE public.health_appointment_status AS ENUM ('requested', 'pending', 'confirmed', 'cancelled', 'completed', 'no_show', 'rescheduled', 'rejected');
CREATE TYPE public.health_consent_scope AS ENUM ('medical_records', 'lab_results', 'prescriptions', 'full');
CREATE TYPE public.health_consent_status AS ENUM ('active', 'revoked', 'expired');
CREATE TYPE public.health_document_category AS ENUM ('medical_report', 'lab_result', 'prescription', 'imaging', 'invoice', 'insurance_document', 'identity_document', 'professional_document', 'administrative_document', 'other');
CREATE TYPE public.health_home_care_status AS ENUM ('requested', 'confirmed', 'in_progress', 'completed', 'cancelled');
CREATE TYPE public.health_invoice_status AS ENUM ('pending', 'paid', 'cancelled', 'refunded');
CREATE TYPE public.health_lab_status AS ENUM ('requested', 'scheduled', 'sample_collected', 'processing', 'completed', 'cancelled');
CREATE TYPE public.health_prescription_status AS ENUM ('active', 'completed', 'cancelled', 'expired');
CREATE TYPE public.health_provider_type AS ENUM ('clinic', 'hospital', 'pharmacy', 'laboratory', 'diagnostic_center', 'home_care_provider', 'other');
CREATE TYPE public.health_verification_status AS ENUM ('pending', 'under_review', 'verified', 'rejected', 'suspended');
CREATE TYPE public.immo_appointment_status AS ENUM ('requested', 'confirmed', 'completed', 'cancelled', 'missed');
CREATE TYPE public.immo_commission_status AS ENUM ('pending', 'approved', 'paid', 'cancelled');
CREATE TYPE public.immo_lease_status AS ENUM ('draft', 'active', 'expired', 'terminated');
CREATE TYPE public.immo_offer_status AS ENUM ('submitted', 'under_review', 'accepted', 'rejected', 'withdrawn', 'expired');
CREATE TYPE public.immo_project_status AS ENUM ('planned', 'under_construction', 'completed', 'delivered', 'suspended');
CREATE TYPE public.immo_property_status AS ENUM ('draft', 'pending_review', 'published', 'reserved', 'rented', 'sold', 'unavailable', 'suspended', 'archived');
CREATE TYPE public.immo_rent_schedule_status AS ENUM ('pending', 'partially_paid', 'paid', 'overdue');
CREATE TYPE public.immo_report_status AS ENUM ('pending', 'approved', 'rejected', 'suspended');
CREATE TYPE public.immo_request_status AS ENUM ('open', 'matched', 'converted', 'closed', 'cancelled');
CREATE TYPE public.immo_reservation_status AS ENUM ('pending', 'confirmed', 'expired', 'cancelled', 'refunded');
CREATE TYPE public.immo_transaction_type AS ENUM ('rent', 'sale', 'short_term_rental', 'reservation', 'lease_to_own');
CREATE TYPE public.immo_unit_status AS ENUM ('available', 'reserved', 'sold', 'rented', 'unavailable');
CREATE TYPE public.immo_verification_status AS ENUM ('unverified', 'submitted', 'under_review', 'verified', 'rejected', 'suspended');
CREATE TYPE public.invitation_status AS ENUM ('pending', 'accepted', 'expired', 'cancelled');
CREATE TYPE public.invoice_status AS ENUM ('draft', 'issued', 'paid', 'partially_paid', 'overdue', 'cancelled');
CREATE TYPE public.kyc_level AS ENUM ('unverified', 'basic', 'verified', 'enhanced');
CREATE TYPE public.kyc_status AS ENUM ('pending', 'under_review', 'approved', 'rejected', 'expired');
CREATE TYPE public.lang_direction AS ENUM ('ltr', 'rtl');
CREATE TYPE public.marketplace_listing_status AS ENUM ('draft', 'pending_review', 'published', 'paused', 'sold_out', 'archived', 'rejected');
CREATE TYPE public.marketplace_message_status AS ENUM ('sent', 'delivered', 'read');
CREATE TYPE public.marketplace_order_status AS ENUM ('pending', 'awaiting_payment', 'paid', 'confirmed', 'preparing', 'ready', 'picked_up', 'in_transit', 'delivered', 'cancelled', 'refunded', 'returned');
CREATE TYPE public.marketplace_refund_status AS ENUM ('pending', 'approved', 'rejected', 'processing', 'completed', 'failed');
CREATE TYPE public.marketplace_return_status AS ENUM ('requested', 'approved', 'rejected', 'received', 'refunded', 'failed');
CREATE TYPE public.marketplace_review_status AS ENUM ('pending', 'published', 'rejected', 'hidden');
CREATE TYPE public.marketplace_seller_status AS ENUM ('pending', 'active', 'suspended', 'rejected');
CREATE TYPE public.marketplace_settlement_status AS ENUM ('pending', 'processing', 'completed', 'failed');
CREATE TYPE public.module_status AS ENUM ('planned', 'development', 'active', 'maintenance', 'disabled');
CREATE TYPE public.notification_type AS ENUM ('info', 'success', 'warning', 'error', 'security', 'transaction', 'marketing', 'system');
CREATE TYPE public.order_status AS ENUM ('pending', 'confirmed', 'processing', 'ready', 'shipped', 'delivered', 'cancelled', 'returned');
CREATE TYPE public.org_member_status AS ENUM ('active', 'suspended', 'invited', 'removed');
CREATE TYPE public.payment_request_status AS ENUM ('pending', 'paid', 'expired', 'cancelled');
CREATE TYPE public.sale_status AS ENUM ('pending', 'confirmed', 'paid', 'partially_paid', 'cancelled', 'refunded');
CREATE TYPE public.subscription_frequency AS ENUM ('daily', 'weekly', 'monthly', 'quarterly', 'yearly');
CREATE TYPE public.subscription_status AS ENUM ('active', 'paused', 'cancelled', 'expired');
CREATE TYPE public.super_admin_status AS ENUM ('active', 'suspended', 'revoked');
CREATE TYPE public.transaction_status AS ENUM ('pending', 'processing', 'completed', 'failed', 'cancelled', 'reversed', 'refunded');
CREATE TYPE public.transaction_type AS ENUM ('deposit', 'withdrawal', 'payment', 'transfer_out', 'transfer_in', 'refund', 'exchange', 'fee', 'adjustment', 'cashback');
CREATE TYPE public.transfer_type AS ENUM ('national', 'regional', 'international');
CREATE TYPE public.transit_case_status AS ENUM ('draft', 'submitted', 'processing', 'awaiting_documents', 'awaiting_customs', 'in_transit', 'arrived', 'cleared', 'ready_for_delivery', 'delivered', 'cancelled', 'closed');
CREATE TYPE public.transit_container_type AS ENUM ('dry', 'reefer', 'open_top', 'flat_rack', 'other');
CREATE TYPE public.transit_customs_status AS ENUM ('pending', 'submitted', 'under_review', 'information_requested', 'cleared', 'rejected', 'on_hold');
CREATE TYPE public.transit_invoice_status AS ENUM ('draft', 'issued', 'partially_paid', 'paid', 'overdue', 'cancelled');
CREATE TYPE public.transit_location_type AS ENUM ('port', 'airport', 'warehouse', 'border', 'terminal', 'hub');
CREATE TYPE public.transit_logistic_unit_type AS ENUM ('pallet', 'crate', 'carton', 'bag', 'container', 'package');
CREATE TYPE public.transit_mode AS ENUM ('road', 'sea', 'air', 'rail', 'multimodal');
CREATE TYPE public.transit_operation_type AS ENUM ('import', 'export', 'transit', 'national', 'international');
CREATE TYPE public.transit_partner_type AS ENUM ('carrier', 'forwarder', 'warehouse_operator', 'handler', 'agent', 'supplier', 'service_provider');
CREATE TYPE public.transit_payment_schedule_status AS ENUM ('pending', 'partially_paid', 'paid', 'overdue', 'cancelled');
CREATE TYPE public.transit_quote_status AS ENUM ('draft', 'sent', 'viewed', 'accepted', 'rejected', 'expired', 'cancelled');
CREATE TYPE public.transit_request_status AS ENUM ('open', 'quoted', 'converted', 'closed', 'cancelled');
CREATE TYPE public.transit_tracking_status AS ENUM ('created', 'picked_up', 'loaded', 'departed', 'in_transit', 'arrived_port', 'customs_processing', 'cleared', 'warehouse', 'out_for_delivery', 'delivered');
CREATE TYPE public.transport_availability_status AS ENUM ('online', 'offline', 'busy', 'scheduled');
CREATE TYPE public.transport_booking_status AS ENUM ('requested', 'searching', 'accepted', 'driver_arriving', 'driver_arrived', 'in_progress', 'completed', 'cancelled', 'failed');
CREATE TYPE public.transport_delivery_status AS ENUM ('created', 'awaiting_pickup', 'picked_up', 'in_transit', 'arrived', 'out_for_delivery', 'delivered', 'failed', 'cancelled', 'returned');
CREATE TYPE public.transport_driver_status AS ENUM ('pending', 'active', 'unavailable', 'suspended', 'rejected', 'inactive');
CREATE TYPE public.transport_rental_status AS ENUM ('pending', 'confirmed', 'active', 'completed', 'cancelled');
CREATE TYPE public.transport_request_status AS ENUM ('open', 'quoted', 'converted', 'closed', 'cancelled');
CREATE TYPE public.transport_review_status AS ENUM ('pending', 'published', 'rejected', 'hidden');
CREATE TYPE public.transport_review_target AS ENUM ('driver', 'vehicle', 'delivery', 'rental');
CREATE TYPE public.transport_seat_status AS ENUM ('available', 'reserved', 'blocked');
CREATE TYPE public.transport_vehicle_status AS ENUM ('active', 'maintenance', 'suspended', 'retired');
CREATE TYPE public.transport_verification_status AS ENUM ('unverified', 'submitted', 'under_review', 'verified', 'rejected', 'suspended');
CREATE TYPE public.travel_booking_status AS ENUM ('pending', 'awaiting_payment', 'confirmed', 'cancelled', 'completed', 'expired', 'refunded', 'partially_refunded');
CREATE TYPE public.travel_publish_status AS ENUM ('draft', 'published', 'unavailable', 'archived');
CREATE TYPE public.travel_quote_status AS ENUM ('draft', 'sent', 'viewed', 'accepted', 'rejected', 'expired');
CREATE TYPE public.travel_request_status AS ENUM ('open', 'quoted', 'converted', 'closed', 'cancelled');
CREATE TYPE public.travel_resource_type AS ENUM ('room', 'activity', 'tour');
CREATE TYPE public.travel_review_status AS ENUM ('pending', 'published', 'rejected', 'hidden');
CREATE TYPE public.travel_target_type AS ENUM ('destination', 'accommodation', 'activity', 'tour', 'agency', 'guide');
CREATE TYPE public.travel_verification_status AS ENUM ('unverified', 'submitted', 'under_review', 'verified', 'rejected', 'suspended');
CREATE TYPE public.wallet_status AS ENUM ('active', 'suspended', 'locked', 'closed');
CREATE TYPE public.webhook_event_status AS ENUM ('received', 'processing', 'processed', 'failed', 'ignored');
