-- LIVE SUPABASE TRIGGER DEFINITIONS

CREATE TRIGGER trg_jdv_ai_protect_message_identity BEFORE INSERT OR UPDATE ON ai_messages FOR EACH ROW EXECUTE FUNCTION jdv_ai_protect_message_identity();
CREATE TRIGGER trg_bill_payments_updated_at BEFORE UPDATE ON bill_payments FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_billers_updated_at BEFORE UPDATE ON billers FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_business_clients_updated_at BEFORE UPDATE ON business_clients FOR EACH ROW EXECUTE FUNCTION update_business_updated_at();
CREATE TRIGGER trg_business_invoices_updated_at BEFORE UPDATE ON business_invoices FOR EACH ROW EXECUTE FUNCTION update_business_updated_at();
CREATE TRIGGER trg_business_products_updated_at BEFORE UPDATE ON business_products FOR EACH ROW EXECUTE FUNCTION update_business_updated_at();
CREATE TRIGGER trg_business_profiles_updated_at BEFORE UPDATE ON business_profiles FOR EACH ROW EXECUTE FUNCTION update_business_updated_at();
CREATE TRIGGER trg_business_sales_updated_at BEFORE UPDATE ON business_sales FOR EACH ROW EXECUTE FUNCTION update_business_updated_at();
CREATE TRIGGER trg_cashback_accounts_updated_at BEFORE UPDATE ON cashback_accounts FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_crm_appointments_updated_at BEFORE UPDATE ON crm_appointments FOR EACH ROW EXECUTE FUNCTION crm_set_updated_at();
CREATE TRIGGER trg_crm_commission_rules_updated_at BEFORE UPDATE ON crm_commission_rules FOR EACH ROW EXECUTE FUNCTION crm_set_updated_at();
CREATE TRIGGER trg_crm_commissions_updated_at BEFORE UPDATE ON crm_commissions FOR EACH ROW EXECUTE FUNCTION crm_set_updated_at();
CREATE TRIGGER trg_crm_credit_terms_updated_at BEFORE UPDATE ON crm_credit_terms FOR EACH ROW EXECUTE FUNCTION crm_set_updated_at();
CREATE TRIGGER trg_crm_fill_schedule_business_id BEFORE INSERT ON crm_payment_schedules FOR EACH ROW EXECUTE FUNCTION crm_fill_schedule_business_id();
CREATE TRIGGER trg_crm_payment_schedules_updated_at BEFORE UPDATE ON crm_payment_schedules FOR EACH ROW EXECUTE FUNCTION crm_set_updated_at();
CREATE TRIGGER trg_jdv_guard_wallet_reuse BEFORE INSERT OR UPDATE ON crm_payments FOR EACH ROW EXECUTE FUNCTION jdv_guard_wallet_transaction_reuse();
CREATE TRIGGER trg_crm_prospecteur_stocks_updated_at BEFORE UPDATE ON crm_prospecteur_stocks FOR EACH ROW EXECUTE FUNCTION crm_set_updated_at();
CREATE TRIGGER trg_crm_prospecteurs_updated_at BEFORE UPDATE ON crm_prospecteurs FOR EACH ROW EXECUTE FUNCTION crm_set_updated_at();
CREATE TRIGGER trg_crm_prospects_updated_at BEFORE UPDATE ON crm_prospects FOR EACH ROW EXECUTE FUNCTION crm_set_updated_at();
CREATE TRIGGER trg_protect_prospect_assignment BEFORE UPDATE ON crm_prospects FOR EACH ROW EXECUTE FUNCTION protect_prospect_assignment();
CREATE TRIGGER trg_crm_targets_updated_at BEFORE UPDATE ON crm_targets FOR EACH ROW EXECUTE FUNCTION crm_set_updated_at();
CREATE TRIGGER trg_exchange_transactions_updated_at BEFORE UPDATE ON exchange_transactions FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_fee_rules_updated_at BEFORE UPDATE ON fee_rules FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER health_protect_appointment_system_fields BEFORE UPDATE ON health_appointments FOR EACH ROW EXECUTE FUNCTION health_protect_appointment_system_fields();
CREATE TRIGGER trg_health_appointments_updated_at BEFORE UPDATE ON health_appointments FOR EACH ROW EXECUTE FUNCTION health_set_updated_at();
CREATE TRIGGER trg_jdv_guard_wallet_reuse BEFORE INSERT OR UPDATE ON health_appointments FOR EACH ROW EXECUTE FUNCTION jdv_guard_wallet_transaction_reuse();
CREATE TRIGGER trg_health_home_care_updated_at BEFORE UPDATE ON health_home_care_requests FOR EACH ROW EXECUTE FUNCTION health_set_updated_at();
CREATE TRIGGER trg_health_lab_orders_updated_at BEFORE UPDATE ON health_laboratory_orders FOR EACH ROW EXECUTE FUNCTION health_set_updated_at();
CREATE TRIGGER health_protect_medical_record_system_fields BEFORE UPDATE ON health_medical_records FOR EACH ROW EXECUTE FUNCTION health_protect_medical_record_system_fields();
CREATE TRIGGER trg_health_professionals_updated_at BEFORE UPDATE ON health_professionals FOR EACH ROW EXECUTE FUNCTION health_set_updated_at();
CREATE TRIGGER trg_jdv_protect_health_professional_system BEFORE UPDATE ON health_professionals FOR EACH ROW EXECUTE FUNCTION jdv_protect_profile_system_fields();
CREATE TRIGGER trg_health_provider_profiles_updated_at BEFORE UPDATE ON health_provider_profiles FOR EACH ROW EXECUTE FUNCTION health_set_updated_at();
CREATE TRIGGER trg_health_services_updated_at BEFORE UPDATE ON health_services FOR EACH ROW EXECUTE FUNCTION health_set_updated_at();
CREATE TRIGGER trg_immo_agencies_updated_at BEFORE UPDATE ON immo_agencies FOR EACH ROW EXECUTE FUNCTION immo_set_updated_at();
CREATE TRIGGER trg_immo_agents_updated_at BEFORE UPDATE ON immo_agents FOR EACH ROW EXECUTE FUNCTION immo_set_updated_at();
CREATE TRIGGER trg_jdv_protect_immo_agent_system BEFORE UPDATE ON immo_agents FOR EACH ROW EXECUTE FUNCTION jdv_protect_profile_system_fields();
CREATE TRIGGER trg_immo_appointments_updated_at BEFORE UPDATE ON immo_appointments FOR EACH ROW EXECUTE FUNCTION immo_set_updated_at();
CREATE TRIGGER trg_immo_developers_updated_at BEFORE UPDATE ON immo_developers FOR EACH ROW EXECUTE FUNCTION immo_set_updated_at();
CREATE TRIGGER trg_immo_leases_protect_system BEFORE UPDATE ON immo_leases FOR EACH ROW EXECUTE FUNCTION immo_protect_lease_financial_fields();
CREATE TRIGGER trg_immo_leases_updated_at BEFORE UPDATE ON immo_leases FOR EACH ROW EXECUTE FUNCTION immo_set_updated_at();
CREATE TRIGGER trg_immo_offers_protect_system BEFORE UPDATE ON immo_offers FOR EACH ROW EXECUTE FUNCTION immo_protect_offer_system_fields();
CREATE TRIGGER trg_immo_offers_updated_at BEFORE UPDATE ON immo_offers FOR EACH ROW EXECUTE FUNCTION immo_set_updated_at();
CREATE TRIGGER trg_immo_projects_updated_at BEFORE UPDATE ON immo_projects FOR EACH ROW EXECUTE FUNCTION immo_set_updated_at();
CREATE TRIGGER trg_immo_properties_protect_system BEFORE UPDATE ON immo_properties FOR EACH ROW EXECUTE FUNCTION immo_protect_property_system_fields();
CREATE TRIGGER trg_immo_properties_publish_stamp BEFORE UPDATE ON immo_properties FOR EACH ROW EXECUTE FUNCTION immo_stamp_published_at();
CREATE TRIGGER trg_immo_properties_slug BEFORE INSERT ON immo_properties FOR EACH ROW EXECUTE FUNCTION immo_generate_property_slug();
CREATE TRIGGER trg_immo_properties_updated_at BEFORE UPDATE ON immo_properties FOR EACH ROW EXECUTE FUNCTION immo_set_updated_at();
CREATE TRIGGER trg_immo_rent_schedules_updated_at BEFORE UPDATE ON immo_rent_schedules FOR EACH ROW EXECUTE FUNCTION immo_set_updated_at();
CREATE TRIGGER trg_jdv_guard_wallet_reuse BEFORE INSERT OR UPDATE ON immo_rent_schedules FOR EACH ROW EXECUTE FUNCTION jdv_guard_wallet_transaction_reuse();
CREATE TRIGGER trg_immo_requests_updated_at BEFORE UPDATE ON immo_requests FOR EACH ROW EXECUTE FUNCTION immo_set_updated_at();
CREATE TRIGGER trg_immo_reservations_updated_at BEFORE UPDATE ON immo_reservations FOR EACH ROW EXECUTE FUNCTION immo_set_updated_at();
CREATE TRIGGER trg_jdv_guard_wallet_reuse BEFORE INSERT OR UPDATE ON immo_reservations FOR EACH ROW EXECUTE FUNCTION jdv_guard_wallet_transaction_reuse();
CREATE TRIGGER trg_immo_units_updated_at BEFORE UPDATE ON immo_units FOR EACH ROW EXECUTE FUNCTION immo_set_updated_at();
CREATE TRIGGER trg_jdv_guard_wallet_reuse BEFORE INSERT OR UPDATE ON insurance_payments FOR EACH ROW EXECUTE FUNCTION jdv_guard_wallet_transaction_reuse();
CREATE TRIGGER trg_jdv_guard_wallet_reuse BEFORE INSERT OR UPDATE ON insurance_premium_schedules FOR EACH ROW EXECUTE FUNCTION jdv_guard_wallet_transaction_reuse();
CREATE TRIGGER trg_kyc_profiles_updated_at BEFORE UPDATE ON kyc_profiles FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_marketplace_cart_items_sync_price BEFORE INSERT OR UPDATE ON marketplace_cart_items FOR EACH ROW EXECUTE FUNCTION marketplace_sync_cart_item_price();
CREATE TRIGGER trg_marketplace_listings_protect_system BEFORE UPDATE ON marketplace_listings FOR EACH ROW EXECUTE FUNCTION marketplace_protect_listing_system_fields();
CREATE TRIGGER trg_marketplace_listings_updated_at BEFORE UPDATE ON marketplace_listings FOR EACH ROW EXECUTE FUNCTION marketplace_set_updated_at();
CREATE TRIGGER trg_jdv_guard_wallet_reuse BEFORE INSERT OR UPDATE ON marketplace_orders FOR EACH ROW EXECUTE FUNCTION jdv_guard_wallet_transaction_reuse();
CREATE TRIGGER trg_marketplace_orders_protect_financial BEFORE UPDATE ON marketplace_orders FOR EACH ROW EXECUTE FUNCTION marketplace_protect_order_financial_fields();
CREATE TRIGGER trg_marketplace_orders_updated_at BEFORE UPDATE ON marketplace_orders FOR EACH ROW EXECUTE FUNCTION marketplace_set_updated_at();
CREATE TRIGGER trg_jdv_guard_wallet_reuse BEFORE INSERT OR UPDATE ON marketplace_refunds FOR EACH ROW EXECUTE FUNCTION jdv_guard_wallet_transaction_reuse();
CREATE TRIGGER trg_marketplace_returns_protect_system BEFORE UPDATE ON marketplace_returns FOR EACH ROW EXECUTE FUNCTION marketplace_protect_return_fields();
CREATE TRIGGER trg_marketplace_reviews_rating AFTER INSERT OR UPDATE ON marketplace_reviews FOR EACH ROW EXECUTE FUNCTION update_listing_rating();
CREATE TRIGGER trg_marketplace_sellers_protect_system BEFORE UPDATE ON marketplace_sellers FOR EACH ROW EXECUTE FUNCTION marketplace_protect_seller_system_fields();
CREATE TRIGGER trg_marketplace_sellers_updated_at BEFORE UPDATE ON marketplace_sellers FOR EACH ROW EXECUTE FUNCTION marketplace_set_updated_at();
CREATE TRIGGER trg_jdv_guard_wallet_reuse BEFORE INSERT OR UPDATE ON marketplace_settlements FOR EACH ROW EXECUTE FUNCTION jdv_guard_wallet_transaction_reuse();
CREATE TRIGGER org_members_updated_at BEFORE UPDATE ON organization_members FOR EACH ROW EXECUTE FUNCTION handle_updated_at();
CREATE TRIGGER organizations_updated_at BEFORE UPDATE ON organizations FOR EACH ROW EXECUTE FUNCTION handle_updated_at();
CREATE TRIGGER trg_pay_beneficiaries_updated_at BEFORE UPDATE ON pay_beneficiaries FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_payment_methods_updated_at BEFORE UPDATE ON payment_methods FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_payment_provider_routes_updated_at BEFORE UPDATE ON payment_provider_routes FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_payment_providers_updated_at BEFORE UPDATE ON payment_providers FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_payment_requests_updated_at BEFORE UPDATE ON payment_requests FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_payment_subscriptions_updated_at BEFORE UPDATE ON payment_subscriptions FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER profiles_updated_at BEFORE UPDATE ON profiles FOR EACH ROW EXECUTE FUNCTION handle_updated_at();
CREATE TRIGGER trg_jdv_protect_pub_advertiser_system BEFORE UPDATE ON pub_advertisers FOR EACH ROW EXECUTE FUNCTION jdv_protect_profile_system_fields();
CREATE TRIGGER trg_jdv_guard_wallet_reuse BEFORE INSERT OR UPDATE ON tontine_contributions FOR EACH ROW EXECUTE FUNCTION jdv_guard_wallet_transaction_reuse();
CREATE TRIGGER trg_jdv_guard_wallet_reuse BEFORE INSERT OR UPDATE ON tontine_payouts FOR EACH ROW EXECUTE FUNCTION jdv_guard_wallet_transaction_reuse();
CREATE TRIGGER trg_transaction_limits_updated_at BEFORE UPDATE ON transaction_limits FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_transfers_updated_at BEFORE UPDATE ON transfers FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_transit_customs_cases_updated_at BEFORE UPDATE ON transit_customs_cases FOR EACH ROW EXECUTE FUNCTION transit_set_updated_at();
CREATE TRIGGER transit_protect_invoice_financial_fields BEFORE UPDATE ON transit_invoices FOR EACH ROW EXECUTE FUNCTION transit_protect_invoice_financial_fields();
CREATE TRIGGER trg_jdv_guard_wallet_reuse BEFORE INSERT OR UPDATE ON transit_invoices FOR EACH ROW EXECUTE FUNCTION jdv_guard_wallet_transaction_reuse();
CREATE TRIGGER trg_transit_invoices_updated_at BEFORE UPDATE ON transit_invoices FOR EACH ROW EXECUTE FUNCTION transit_set_updated_at();
CREATE TRIGGER transit_protect_operation_system_fields BEFORE UPDATE ON transit_operations FOR EACH ROW EXECUTE FUNCTION transit_protect_operation_system_fields();
CREATE TRIGGER trg_transit_operations_status_audit AFTER UPDATE ON transit_operations FOR EACH ROW EXECUTE FUNCTION transit_audit_operation_status();
CREATE TRIGGER trg_transit_operations_updated_at BEFORE UPDATE ON transit_operations FOR EACH ROW EXECUTE FUNCTION transit_set_updated_at();
CREATE TRIGGER transit_protect_quote_system_fields BEFORE UPDATE ON transit_quotes FOR EACH ROW EXECUTE FUNCTION transit_protect_quote_system_fields();
CREATE TRIGGER trg_transit_quotes_updated_at BEFORE UPDATE ON transit_quotes FOR EACH ROW EXECUTE FUNCTION transit_set_updated_at();
CREATE TRIGGER transit_protect_request_system_fields BEFORE UPDATE ON transit_requests FOR EACH ROW EXECUTE FUNCTION transit_protect_request_system_fields();
CREATE TRIGGER trg_transit_requests_updated_at BEFORE UPDATE ON transit_requests FOR EACH ROW EXECUTE FUNCTION transit_set_updated_at();
CREATE TRIGGER transit_protect_shipment_system_fields BEFORE UPDATE ON transit_shipments FOR EACH ROW EXECUTE FUNCTION transit_protect_shipment_system_fields();
CREATE TRIGGER trg_transit_shipments_updated_at BEFORE UPDATE ON transit_shipments FOR EACH ROW EXECUTE FUNCTION transit_set_updated_at();
CREATE TRIGGER transit_protect_tracking_system_fields BEFORE UPDATE ON transit_tracking_events FOR EACH ROW EXECUTE FUNCTION transit_protect_tracking_system_fields();
CREATE TRIGGER transport_protect_booking_system_fields BEFORE UPDATE ON transport_bookings FOR EACH ROW EXECUTE FUNCTION transport_protect_booking_system_fields();
CREATE TRIGGER trg_jdv_guard_wallet_reuse BEFORE INSERT OR UPDATE ON transport_bookings FOR EACH ROW EXECUTE FUNCTION jdv_guard_wallet_transaction_reuse();
CREATE TRIGGER trg_transport_bookings_updated_at BEFORE UPDATE ON transport_bookings FOR EACH ROW EXECUTE FUNCTION transport_set_updated_at();
CREATE TRIGGER trg_jdv_guard_wallet_reuse BEFORE INSERT OR UPDATE ON transport_deliveries FOR EACH ROW EXECUTE FUNCTION jdv_guard_wallet_transaction_reuse();
CREATE TRIGGER trg_transport_deliveries_updated_at BEFORE UPDATE ON transport_deliveries FOR EACH ROW EXECUTE FUNCTION transport_set_updated_at();
CREATE TRIGGER transport_protect_delivery_proof_system_fields BEFORE UPDATE ON transport_delivery_proofs FOR EACH ROW EXECUTE FUNCTION transport_protect_delivery_proof_system_fields();
CREATE TRIGGER trg_transport_availability_touch BEFORE UPDATE ON transport_driver_availability FOR EACH ROW EXECUTE FUNCTION transport_touch_availability();
CREATE TRIGGER transport_protect_driver_system_fields BEFORE UPDATE ON transport_drivers FOR EACH ROW EXECUTE FUNCTION transport_protect_driver_system_fields();
CREATE TRIGGER trg_transport_drivers_updated_at BEFORE UPDATE ON transport_drivers FOR EACH ROW EXECUTE FUNCTION transport_set_updated_at();
CREATE TRIGGER trg_transport_pricing_rules_updated_at BEFORE UPDATE ON transport_pricing_rules FOR EACH ROW EXECUTE FUNCTION transport_set_updated_at();
CREATE TRIGGER trg_jdv_guard_wallet_reuse BEFORE INSERT OR UPDATE ON transport_rentals FOR EACH ROW EXECUTE FUNCTION jdv_guard_wallet_transaction_reuse();
CREATE TRIGGER trg_transport_rentals_overlap BEFORE INSERT OR UPDATE ON transport_rentals FOR EACH ROW EXECUTE FUNCTION transport_check_rental_overlap();
CREATE TRIGGER trg_transport_rentals_updated_at BEFORE UPDATE ON transport_rentals FOR EACH ROW EXECUTE FUNCTION transport_set_updated_at();
CREATE TRIGGER trg_transport_requests_updated_at BEFORE UPDATE ON transport_requests FOR EACH ROW EXECUTE FUNCTION transport_set_updated_at();
CREATE TRIGGER trg_transport_routes_updated_at BEFORE UPDATE ON transport_routes FOR EACH ROW EXECUTE FUNCTION transport_set_updated_at();
CREATE TRIGGER trg_transport_schedules_updated_at BEFORE UPDATE ON transport_schedules FOR EACH ROW EXECUTE FUNCTION transport_set_updated_at();
CREATE TRIGGER trg_jdv_guard_wallet_reuse BEFORE INSERT OR UPDATE ON transport_seat_reservations FOR EACH ROW EXECUTE FUNCTION jdv_guard_wallet_transaction_reuse();
CREATE TRIGGER transport_protect_vehicle_system_fields BEFORE UPDATE ON transport_vehicles FOR EACH ROW EXECUTE FUNCTION transport_protect_vehicle_system_fields();
CREATE TRIGGER trg_transport_vehicles_updated_at BEFORE UPDATE ON transport_vehicles FOR EACH ROW EXECUTE FUNCTION transport_set_updated_at();
CREATE TRIGGER trg_travel_accommodations_updated_at BEFORE UPDATE ON travel_accommodations FOR EACH ROW EXECUTE FUNCTION travel_set_updated_at();
CREATE TRIGGER trg_travel_activities_updated_at BEFORE UPDATE ON travel_activities FOR EACH ROW EXECUTE FUNCTION travel_set_updated_at();
CREATE TRIGGER travel_protect_agency_system_fields BEFORE UPDATE ON travel_agencies FOR EACH ROW EXECUTE FUNCTION travel_protect_agency_system_fields();
CREATE TRIGGER trg_travel_agencies_updated_at BEFORE UPDATE ON travel_agencies FOR EACH ROW EXECUTE FUNCTION travel_set_updated_at();
CREATE TRIGGER travel_protect_agent_system_fields BEFORE UPDATE ON travel_agents FOR EACH ROW EXECUTE FUNCTION travel_protect_agent_system_fields();
CREATE TRIGGER trg_travel_agents_updated_at BEFORE UPDATE ON travel_agents FOR EACH ROW EXECUTE FUNCTION travel_set_updated_at();
CREATE TRIGGER travel_protect_availability_reserved_units BEFORE UPDATE ON travel_availability FOR EACH ROW EXECUTE FUNCTION travel_protect_availability_reserved_units();
CREATE TRIGGER trg_travel_availability_updated_at BEFORE UPDATE ON travel_availability FOR EACH ROW EXECUTE FUNCTION travel_set_updated_at();
CREATE TRIGGER travel_protect_booking_system_fields BEFORE UPDATE ON travel_bookings FOR EACH ROW EXECUTE FUNCTION travel_protect_booking_system_fields();
CREATE TRIGGER trg_jdv_guard_wallet_reuse BEFORE INSERT OR UPDATE ON travel_bookings FOR EACH ROW EXECUTE FUNCTION jdv_guard_wallet_transaction_reuse();
CREATE TRIGGER trg_travel_bookings_updated_at BEFORE UPDATE ON travel_bookings FOR EACH ROW EXECUTE FUNCTION travel_set_updated_at();
CREATE TRIGGER travel_protect_commission_system_fields BEFORE UPDATE ON travel_commissions FOR EACH ROW EXECUTE FUNCTION travel_protect_commission_system_fields();
CREATE TRIGGER trg_travel_destinations_slug BEFORE INSERT ON travel_destinations FOR EACH ROW EXECUTE FUNCTION travel_generate_slug();
CREATE TRIGGER trg_travel_destinations_updated_at BEFORE UPDATE ON travel_destinations FOR EACH ROW EXECUTE FUNCTION travel_set_updated_at();
CREATE TRIGGER trg_travel_guides_updated_at BEFORE UPDATE ON travel_guides FOR EACH ROW EXECUTE FUNCTION travel_set_updated_at();
CREATE TRIGGER trg_travel_itineraries_updated_at BEFORE UPDATE ON travel_itineraries FOR EACH ROW EXECUTE FUNCTION travel_set_updated_at();
CREATE TRIGGER travel_protect_quote_system_fields BEFORE UPDATE ON travel_quotes FOR EACH ROW EXECUTE FUNCTION travel_protect_quote_system_fields();
CREATE TRIGGER trg_travel_quotes_updated_at BEFORE UPDATE ON travel_quotes FOR EACH ROW EXECUTE FUNCTION travel_set_updated_at();
CREATE TRIGGER trg_travel_requests_updated_at BEFORE UPDATE ON travel_requests FOR EACH ROW EXECUTE FUNCTION travel_set_updated_at();
CREATE TRIGGER trg_travel_rooms_updated_at BEFORE UPDATE ON travel_rooms FOR EACH ROW EXECUTE FUNCTION travel_set_updated_at();
CREATE TRIGGER trg_travel_tours_updated_at BEFORE UPDATE ON travel_tours FOR EACH ROW EXECUTE FUNCTION travel_set_updated_at();
CREATE TRIGGER trg_wallets_updated_at BEFORE UPDATE ON wallets FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER trg_webhook_events_updated_at BEFORE UPDATE ON webhook_events FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
