-- Historical migration placeholder: 20260920012044 jdv_core_separate_concepteur_and_business_owner
-- Original SQL body is not recoverable from Supabase migration metadata.
-- Current schema is preserved in supabase/snapshot/.
