-- Historical migration placeholder: 20260919205743 jdv_ai_admin_dashboard_v10
-- Original SQL body is not recoverable from Supabase migration metadata.
-- Current schema is preserved in supabase/snapshot/.
