-- Historical migration placeholder: 20260920004451 tontine_president_schedule_penalty_and_beneficiary_phone_v2
-- Original SQL body is not recoverable from Supabase migration metadata.
-- Current schema is preserved in supabase/snapshot/.
