-- Historical migration placeholder: 20260919121438 transport_04_reviews_reports
-- Original SQL body is not recoverable from Supabase migration metadata.
-- Current schema is preserved in supabase/snapshot/.
