-- Historical migration placeholder: 20260920005321 jdv_tontine_phase4b_cycle_dashboard
-- Original SQL body is not recoverable from Supabase migration metadata.
-- Current schema is preserved in supabase/snapshot/.
