-- Historical migration placeholder: 20260918201712 crm_01_enums_and_prospecting
-- Original SQL body is not recoverable from Supabase migration metadata.
-- Current schema is preserved in supabase/snapshot/.
