-- Historical migration placeholder: 20260919205948 jdv_ai_provider_admin_v12
-- Original SQL body is not recoverable from Supabase migration metadata.
-- Current schema is preserved in supabase/snapshot/.
