-- Historical migration placeholder: 20260919121529 transport_05_rls_policies
-- Original SQL body is not recoverable from Supabase migration metadata.
-- Current schema is preserved in supabase/snapshot/.
