-- Historical migration placeholder: 20260920013816 jdv_marketplace_secure_order_creation
-- Original SQL body is not recoverable from Supabase migration metadata.
-- Current schema is preserved in supabase/snapshot/.
