-- Historical migration placeholder: 20260920035228 jdv_agriculture_interface_foundation
-- Original SQL body is not recoverable from Supabase migration metadata.
-- Current schema is preserved in supabase/snapshot/.
