-- Historical migration placeholder: 20260919204643 jdv_ai_controlled_query_v5
-- Original SQL body is not recoverable from Supabase migration metadata.
-- Current schema is preserved in supabase/snapshot/.
