-- Historical migration placeholder: 20260921195826 health_04_documents_prescriptions_lab_homecare
-- Original SQL body is not recoverable from Supabase migration metadata.
-- Current schema is preserved in supabase/snapshot/.
