-- Historical migration placeholder: 20260919201906 harden_transport_payments_access_v1
-- Original SQL body is not recoverable from Supabase migration metadata.
-- Current schema is preserved in supabase/snapshot/.
