-- Historical migration placeholder: 20260920003516 jdv_tontine_phase2_engine
-- Original SQL body is not recoverable from Supabase migration metadata.
-- Current schema is preserved in supabase/snapshot/.
