-- Historical migration placeholder: 20260919200617 harden_travel_booking_crm_security_v1
-- Original SQL body is not recoverable from Supabase migration metadata.
-- Current schema is preserved in supabase/snapshot/.
