-- Historical migration placeholder: 20260919205558 jdv_ai_quotas_models_v9
-- Original SQL body is not recoverable from Supabase migration metadata.
-- Current schema is preserved in supabase/snapshot/.
