-- Historical migration placeholder: 20260920020150 jdv_profile_system_fields_integrity
-- Original SQL body is not recoverable from Supabase migration metadata.
-- Current schema is preserved in supabase/snapshot/.
