-- Historical migration placeholder: 20260919071848 transport_03_routes_schedules_seats
-- Original SQL body is not recoverable from Supabase migration metadata.
-- Current schema is preserved in supabase/snapshot/.
