-- Historical migration placeholder: 20260920003310 jdv_tontine_foundation
-- Original SQL body is not recoverable from Supabase migration metadata.
-- Current schema is preserved in supabase/snapshot/.
