-- Historical migration placeholder: 20260920013803 jdv_marketplace_harden_financial_and_owner_integrity
-- Original SQL body is not recoverable from Supabase migration metadata.
-- Current schema is preserved in supabase/snapshot/.
