-- Historical migration placeholder: 20260919205855 jdv_ai_provider_management_v11
-- Original SQL body is not recoverable from Supabase migration metadata.
-- Current schema is preserved in supabase/snapshot/.
