-- Historical migration placeholder: 20260919071806 transport_01_types_vehicles_drivers
-- Original SQL body is not recoverable from Supabase migration metadata.
-- Current schema is preserved in supabase/snapshot/.
