-- Historical migration placeholder: 20260920220124 fix_module_status_no_frontend_yet
-- Original SQL body is not recoverable from Supabase migration metadata.
-- Current schema is preserved in supabase/snapshot/.
