-- Historical migration placeholder: 20260920021027 jdv_cross_module_exact_payment_integrity_v1
-- Original SQL body is not recoverable from Supabase migration metadata.
-- Current schema is preserved in supabase/snapshot/.
