-- Historical migration placeholder: 20260919122503 transit_05_requests_reports
-- Original SQL body is not recoverable from Supabase migration metadata.
-- Current schema is preserved in supabase/snapshot/.
