-- Historical migration placeholder: 20260920014736 jdv_health_harden_production_security
-- Original SQL body is not recoverable from Supabase migration metadata.
-- Current schema is preserved in supabase/snapshot/.
