-- Historical migration placeholder: 20260918201949 crm_06_rls_policies
-- Original SQL body is not recoverable from Supabase migration metadata.
-- Current schema is preserved in supabase/snapshot/.
