-- Historical migration placeholder: 20260919203925 jdv_ai_foundations_v1
-- Original SQL body is not recoverable from Supabase migration metadata.
-- Current schema is preserved in supabase/snapshot/.
