-- Historical migration placeholder: 20260919071629 travel_05_favorites_reviews_reports
-- Original SQL body is not recoverable from Supabase migration metadata.
-- Current schema is preserved in supabase/snapshot/.
