-- Historical migration placeholder: 20260919194551 secure_module_functions_search_path
-- Original SQL body is not recoverable from Supabase migration metadata.
-- Current schema is preserved in supabase/snapshot/.
