-- Historical migration placeholder: 20260918201837 crm_05_documents_conversion_indexes
-- Original SQL body is not recoverable from Supabase migration metadata.
-- Current schema is preserved in supabase/snapshot/.
