-- Historical migration placeholder: 20260919122304 create_business_admin_account_romarica15_part2
-- Original SQL body is not recoverable from Supabase migration metadata.
-- Current schema is preserved in supabase/snapshot/.
