-- Historical migration placeholder: 20260920002626 harden_transport_security_definer_functions
-- Original SQL body is not recoverable from Supabase migration metadata.
-- Current schema is preserved in supabase/snapshot/.
