-- Historical migration placeholder: 20260919071501 travel_02_activities_tours_availability
-- Original SQL body is not recoverable from Supabase migration metadata.
-- Current schema is preserved in supabase/snapshot/.
