-- Historical migration placeholder: 20260920084141 fix_module_statuses_no_frontend
-- Original SQL body is not recoverable from Supabase migration metadata.
-- Current schema is preserved in supabase/snapshot/.
