-- Historical migration placeholder: 20260920021709 jdv_cleanup_duplicate_health_index_v1
-- Original SQL body is not recoverable from Supabase migration metadata.
-- Current schema is preserved in supabase/snapshot/.
